import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { CSSProperties, ReactElement } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ChevronLeft, CircleHelp, Pause, Play, RotateCcw, Trophy } from 'lucide-react';
import { Robot } from '../components/Artwork';
import { createSnake, setDirection, tick } from '../game/snake/engine';
import type { Direction, SnakeState } from '../game/snake/engine';
import { sound, unlockAudio } from '../game/audio';
export default function SnakeGame({ onHelp }: { onHelp: () => void }) {
  const [state, setState] = useState<SnakeState>(() => createSnake()); const [paused, setPaused] = useState(false); const stage = useRef<HTMLDivElement>(null); const [size, setSize] = useState(32);
  useLayoutEffect(() => { const update = () => { if (!stage.current) return; const r = stage.current.getBoundingClientRect(); setSize(Math.max(18, Math.floor(Math.min((r.width - 20) / state.cols, (r.height - 20) / state.rows)))); }; update(); const o = new ResizeObserver(update); if (stage.current) o.observe(stage.current); return () => o.disconnect(); }, [state.cols, state.rows]);
  useEffect(() => { const id = window.setInterval(() => { if (!paused) setState(s => { const n = tick(s); if (n.score > s.score) sound('boost'); if (n.status === 'lost' && s.status === 'playing') sound('lose'); if (n.status === 'won' && s.status === 'playing') sound('win'); return n; }); }, 360); return () => clearInterval(id); }, [paused]);
  useEffect(() => { const key = (e: KeyboardEvent) => { const map: Record<string, Direction> = { ArrowUp: 'up', w: 'up', ArrowDown: 'down', s: 'down', ArrowLeft: 'left', a: 'left', ArrowRight: 'right', d: 'right' }; if (map[e.key]) { e.preventDefault(); unlockAudio(); setState(s => setDirection(s, map[e.key])); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
  const restart = () => { unlockAudio(); setPaused(false); setState(createSnake()); }; const move = (d: Direction) => { unlockAudio(); setState(s => setDirection(s, d)); }; const directions: { d: Direction; icon: ReactElement; label: string }[] = [{ d: 'up', icon: <ArrowUp/>, label: '向上移动' }, { d: 'left', icon: <ArrowLeft/>, label: '向左移动' }, { d: 'down', icon: <ArrowDown/>, label: '向下移动' }, { d: 'right', icon: <ArrowRight/>, label: '向右移动' }];
  return <><div className="game-breadcrumb"><a href="#/"><ChevronLeft size={16}/>返回探索乐园</a><span>/</span><span>机器人贪吃蛇</span></div><div className="game-heading"><div><div className="eyebrow"><span/> ROBOT SNACK RUN</div><h1>机器人贪吃蛇 <span>✦</span></h1><p>收集能量电池，让机器人变得更长更强！</p></div><div className="game-heading-actions"><button className="button secondary small" onClick={onHelp}><CircleHelp size={17}/>怎么玩</button><button className="icon-button bordered" aria-label={paused ? '继续游戏' : '暂停游戏'} onClick={() => setPaused(p => !p)}>{paused ? <Play size={19}/> : <Pause size={19}/>}</button></div></div><div className="snake-layout"><section className="snake-panel"><div className="snake-topbar"><span><Trophy size={16}/> 能量收集</span><strong>{state.score}<small> 个</small></strong><button className="icon-button bordered" aria-label="重新开始" onClick={restart}><RotateCcw size={17}/></button></div><div ref={stage} className="snake-stage"><div className="snake-board" style={{ '--cols': state.cols, '--rows': state.rows, '--cell': `${size}px` } as CSSProperties}>{Array.from({ length: state.rows * state.cols }, (_, i) => { const p = { x: i % state.cols, y: Math.floor(i / state.cols) }; const body = state.snake.findIndex(s => s.x === p.x && s.y === p.y); const food = state.food.x === p.x && state.food.y === p.y; return <div key={i} className={`snake-cell ${body >= 0 ? 'snake-body' : ''} ${body === 0 ? 'snake-head' : ''} ${food ? 'snake-food' : ''}`}><span>{body === 0 ? <Robot/> : food ? '⚡' : ''}</span></div>; })}</div>{(paused || state.status !== 'playing') && <div className="snake-overlay"><strong>{state.status === 'won' ? '能量收集完成！' : state.status === 'lost' ? '撞到障碍啦' : '游戏暂停'}</strong><p>{state.status === 'won' ? '你打造了一条超长能量链！' : state.status === 'lost' ? '再试一次，规划好下一步。' : '准备好后继续前进。'}</p><button className="button primary" onClick={state.status === 'playing' ? () => setPaused(false) : restart}>{state.status === 'playing' ? '继续游戏' : '再来一局'}<RotateCcw size={17}/></button></div>}</div></section><aside className="snake-side"><div className="snake-mission"><span className="eyebrow">CURRENT MISSION</span><h2>找到闪电电池</h2><p>每收集一颗电池，机器人就会变长。小心别撞到自己或边界哦！</p></div><div className="snake-controls"><strong>移动机器人</strong><div className="direction-pad">{directions.map(({ d, icon, label }) => <button key={d} aria-label={label} onClick={() => move(d)}>{icon}</button>)}</div><small>方向键 / WASD 也可以</small></div></aside></div></>;
}
