import { useEffect, useState } from 'react';
import { ArrowUpRight, BookOpen, ChevronRight, Compass, Gamepad2, Heart, HelpCircle, Leaf, Medal, Rocket, Sparkles, Star, Trophy, Volume2, VolumeX, Zap } from 'lucide-react';
import { HeroArt, Landscape, Robot } from './components/Artwork';
import Modal from './components/Modal';
import Game from './pages/Game';
import OceanGame from './pages/OceanGame';
import SnakeGame from './pages/SnakeGame';
import { loadOceanProgress, saveOceanProgress } from './game/ocean/storage';
import { WORDS, wordSpriteStyle } from './game/ocean/engine';
import { loadProgress, saveProgress } from './game/storage';
import type { Progress } from './game/storage';
import { setSoundEnabled, sound, unlockAudio } from './game/audio';
export default function App() {
  const [route, setRoute] = useState(location.hash || '#/');
  const [progress, setProgress] = useState<Progress>(loadProgress);
  const [oceanProgress, setOceanProgress] = useState(loadOceanProgress);
  useEffect(() => { saveOceanProgress(oceanProgress); }, [oceanProgress]);
  const [help, setHelp] = useState(false);
  const [notice, setNotice] = useState(false);
  useEffect(() => { const handler = () => setRoute(location.hash || '#/'); window.addEventListener('hashchange', handler); return () => window.removeEventListener('hashchange', handler); }, []);
  useEffect(() => { saveProgress(progress); setSoundEnabled(progress.sound); }, [progress]);
  const ocean = route.startsWith('#/games/ocean'); const snake = route.startsWith('#/games/snake');
  const game = route.startsWith('#/games/energy') || ocean || snake; const achievements = route === '#/achievements';
  function start() { unlockAudio(); sound('click'); location.hash = '/games/energy'; }
  function startOcean() { unlockAudio(); sound('click'); location.hash = '/games/ocean'; }
  function startSnake() { unlockAudio(); sound('click'); location.hash = '/games/snake'; }
  function oceanWin(energy: number, _monsters: number, level: number) { setOceanProgress(p => ({ ...p, wins: p.wins + 1, stars: p.stars + (energy >= 70 ? 3 : energy >= 35 ? 2 : 1), highestLevel: Math.max(p.highestLevel, Math.min(9, level + 1)) })); }
  function oceanAttempt(id: string, correct: boolean, missed: string[]) { setOceanProgress(p => ({ ...p, correct: p.correct + (correct ? 1 : 0), learned: correct ? [...new Set([...p.learned, id])] : p.learned, missed })); }
  function win(energy: number, monsters: number, level: number) { setProgress(p => ({ ...p, wins: p.wins + 1, stars: p.stars + (energy >= 70 ? 3 : energy >= 35 ? 2 : 1), monsters: p.monsters + monsters, highestLevel: Math.max(p.highestLevel, Math.min(9, level + 1)) })); }
  return <div className={game ? `app-shell game-shell ${ocean ? "ocean-shell" : snake ? "snake-shell" : ""}` : "app-shell"}><header className="site-header"><a className="brand" href="#/" aria-label="小小探险家首页"><span className="brand-icon"><Robot/></span><span>小小探险家<small>LITTLE EXPLORER</small></span></a><nav aria-label="主导航"><a href="#/" className={!achievements ? 'active' : ''}><Compass size={18}/>探索乐园</a><a href="#/achievements" className={achievements ? 'active' : ''}><Medal size={18}/>我的成就</a></nav><div className="header-actions"><button className="icon-button sound-toggle" onClick={() => { unlockAudio(); setProgress(p => ({ ...p, sound: !p.sound })); }} aria-label={progress.sound ? '关闭声音' : '开启声音'} title={progress.sound ? '关闭声音' : '开启声音'}>{progress.sound ? <Volume2 size={20}/> : <VolumeX size={20}/>}</button><span className="header-divider"/><span className="explorer-avatar"><Robot/></span><div className="explorer-name">小小探险家<small><span/> 准备好出发啦</small></div></div></header>
  <main className={game ? 'main game-main' : 'main'}>{ocean ? <OceanGame onWin={oceanWin} onHelp={() => setHelp(true)} onAttempt={oceanAttempt} soundEnabled={progress.sound}/> : snake ? <SnakeGame onHelp={() => setHelp(true)}/> : game ? <Game onWin={win} onHelp={() => setHelp(true)}/> : achievements ? <section className="achievements-page"><div className="eyebrow"><Trophy size={16}/> MY LITTLE MILESTONES</div><h1>每一步，都值得闪闪发光<span> ✦</span></h1><p className="section-subtitle">这里珍藏着你的勇气、智慧，和每一次小小的进步。</p><div className="achievement-stats"><div><Star/><strong>{progress.stars}</strong><span>收集的星星</span></div><div><FlagIcon/><strong>{progress.wins}</strong><span>完成的探险</span></div><div><Zap/><strong>{progress.monsters}</strong><span>战胜的小怪兽</span></div></div><div className="badge-grid">{[{icon:<Rocket/>,name:'勇敢第一步',desc:'完成第一次能量迷宫',done:progress.wins>0},{icon:<Star/>,name:'星星收藏家',desc:'累计收集 9 颗星星',done:progress.stars>=9},{icon:<BookOpen/>,name:'数学小达人',desc:'累计答对 10 道怪兽谜题',done:progress.monsters>=10}].map(b=><div key={b.name} className={`badge-card ${b.done?'earned':''}`}><div>{b.icon}</div><h3>{b.name}</h3><p>{b.desc}</p><span>{b.done?'已获得 · 你真棒！':'等待你的探索'}</span></div>)}</div><section className="ocean-achievements"><div><span className="eyebrow">MY OCEAN DISCOVERIES</span><h2>海底单词收藏册</h2><p>{oceanProgress.wins} 次寻宝成功 · {oceanProgress.stars} 颗海洋星星 · {oceanProgress.correct} 次答对</p><p>已认识 {oceanProgress.learned.length} / 63 个单词 · {oceanProgress.missed.length} 个等待复习</p></div><div className="ocean-word-review">{oceanProgress.learned.map(id => { const word = WORDS.find(w => w.id === id)!; return <span key={id}><span className="word-review-sprite" style={wordSpriteStyle(word)} aria-hidden="true"/>{word.english}<small>{word.chinese}</small></span>; })}</div><button className="button secondary" onClick={startOcean}>继续海底寻宝 <ChevronRight size={18}/></button></section><button className="button primary" onClick={start}>继续收集小成就 <ChevronRight size={18}/></button><p className="save-note">探险记录保存在当前浏览器中。</p></section> : <>
    <div className="welcome-row"><span><span className="sun-icon">☀</span> 你好呀，小小探险家！</span><span className="welcome-tag"><span/> 好奇心已就位</span></div>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> 为每一颗好奇的小脑袋</div><h1>小小机器人，<br/>大大的<span className="underlined">冒险世界<svg viewBox="0 0 280 15"><path d="M3 10Q120-2 276 7"/></svg></span><span className="title-star">✦</span></h1><p>和机器人伙伴一起，动动脑、闯闯关。<br/>把每一次尝试，都变成了不起的成长！</p><button className="button primary hero-button" onClick={start}>开始我的探险 <ArrowUpRight size={20}/></button><div className="hero-notes"><span><span className="tiny-check">✓</span> 边玩边学</span><span><span className="tiny-check">✓</span> 鼓励每次尝试</span><span><span className="tiny-check">✓</span> 简单好上手</span></div></div><HeroArt/><div className="hero-corner">LET’S EXPLORE TOGETHER <span>↗</span></div></section>
    <section className="games-section"><div className="section-heading"><div><div className="section-title"><span className="section-icon"><Gamepad2 size={23}/></span><h2>挑一个世界，出发吧</h2><span className="count-pill">03 / 03</span></div><p>每个小世界，都藏着一个新发现。</p></div><span className="section-aside"><Sparkles size={16}/> 冒险还在不断生长</span></div><div className="game-cards"><article className="game-card available" onClick={start}><div className="game-cover"><Landscape/><span className="cover-tag"><span/> 开放探索</span><span className="game-number">01</span></div><div className="game-card-body"><div className="card-title"><h3>彩虹能量迷宫</h3><span className="age-tag">5 岁＋</span></div><p>收集能量，智斗小怪兽，<br/>带机器人找到回家的路。</p><div className="skill-tags"><span><Zap size={12}/> 策略思考</span><span><BookOpen size={12}/> 趣味数学</span></div><div className="card-footer"><span><span className="difficulty-dots">● ● <i>●</i></span> 轻松入门</span><button className="round-arrow" aria-label="开始彩虹能量迷宫" onClick={e=>{e.stopPropagation();start();}}><ArrowUpRight size={20}/></button></div></div></article>
    <article className="game-card available snake-game-card" onClick={startSnake}><div className="game-cover"><Landscape variant="space"/><span className="cover-tag"><span/> 开放探索</span><span className="game-number">02</span></div><div className="game-card-body"><div className="card-title"><h3>机器人贪吃蛇</h3><span className="age-tag">5 岁＋</span></div><p>收集闪电电池，让机器人变长，<br/>灵活避开边界和自己的身体。</p><div className="skill-tags"><span>反应力</span><span>空间规划</span></div><div className="card-footer"><span>收集电池 · 灵活移动</span><button className="round-arrow" aria-label="开始机器人贪吃蛇" onClick={e=>{e.stopPropagation();startSnake();}}><ArrowUpRight size={20}/></button></div></div></article>
    <article className="game-card available ocean-game-card" onClick={startOcean}><div className="game-cover"><Landscape variant="ocean"/><span className="cover-tag"><span/> 开放探索</span><span className="game-number">03</span></div><div className="game-card-body"><div className="card-title"><h3>深海单词寻宝</h3><span className="age-tag">5 岁＋</span></div><p>读懂单词，找到图片，<br/>和小绿一起开启海底宝箱。</p><div className="skill-tags"><span><BookOpen size={12}/> 英语启蒙</span><span>观察与探索</span></div><div className="card-footer"><span>63 个单词 · 9 关冒险</span><button className="round-arrow" aria-label="开始深海单词寻宝" onClick={e => { e.stopPropagation(); startOcean(); }}><ArrowUpRight size={20}/></button></div></div></article></div></section>
    <section className="encouragement"><span className="heart-doodle"><Heart size={27}/></span><div><h3>不怕走错路，每一次尝试都很酷。</h3><p>这里没有倒计时，不用着急。按自己的节奏，慢慢发现，快乐成长。</p></div><span className="encouragement-art">✧ <span>✦</span></span></section>
  </>}</main><footer className="site-footer"><span><Leaf size={15}/> 为好奇心充电，为想象力出发。</span><div><button onClick={()=>setNotice(true)}>给家长的话</button><span>·</span><button onClick={()=>setHelp(true)}><HelpCircle size={14}/> 玩法帮助</button><span className="footer-sign">MADE FOR LITTLE EXPLORERS</span></div></footer>
  {help && <Modal title="探险小指南" className={ocean ? "ocean-help-modal" : ""} onClose={()=>setHelp(false)}><span className="modal-symbol"><Compass size={30}/></span><h2>探险小指南</h2><p className="modal-intro">不用着急，和小机器人一步步前进。</p><div className="help-list"><p><span>01</span><span><b>从左上角出发</b>点击上下左右相邻格子，或使用方向键 / WASD。</span></p><p><span>02</span><span><b>{ocean ? "收集氧气泡" : "收集绿色能量"}</b>{ocean ? "氧气泡 +15，海流消耗能量。每格只触发一次，能量归零需要重新出发。" : "绿色 +15，橙色扣能量。每格只触发一次，能量归零会爆炸哦。"}</span></p><p><span>03</span><span><b>{ocean ? "读单词，选图片" : "用智慧战胜小怪兽"}</b>{ocean ? "从四张图片里找到英文单词对应的物品。答错扣 10 点能量后继续尝试；放弃扣 1 点，留在原地。" : "回答 20 以内加减法，答对才能前进；也可放弃，扣 1 点能量并留在原地。"}</span></p><p><span>04</span><span><b>{ocean ? "打开右下角的宝箱" : "到达右下角的终点"}</b>{ocean ? "至少完成一次单词挑战才能开箱。" : ""}剩余能量越多，收集到的星星越多，最高 3 颗！</span></p></div><button className="button primary full-width" onClick={()=>setHelp(false)}>明白啦，出发！<Rocket size={18}/></button></Modal>}
  {notice && <Modal title="给家长的话" onClose={()=>setNotice(false)}><span className="modal-symbol"><Heart size={30}/></span><h2>给每一位大朋友</h2><p className="parent-copy">小小探险家是一个让孩子自由尝试的小游戏乐园。彩虹能量迷宫结合路线规划与趣味数学；深海单词寻宝通过图片挑战认识 63 个常见英文单词。</p><p className="parent-copy">没有倒计时，没有广告，也无需注册。建议每次玩 10–15 分钟，并鼓励孩子说一说：“为什么选择这条路？”失败只是新的开始。</p><p className="parent-copy">音效可以随时关闭。成就仅保存在当前设备的浏览器里，清除浏览器数据会重置记录。</p><button className="button primary full-width" onClick={()=>setNotice(false)}>一起守护好奇心 <Heart size={17}/></button></Modal>}</div>;
}
function FlagIcon(){return <Trophy/>;}
